# Generated by Django 6.0 on 2025-12-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
